#version: '3.8' # Define a versão da sintaxe do Docker Compose

# Define os serviços que compõem sua aplicação
services:
  # Serviço do Banco de Dados PostgreSQL
  db:
    image: postgres:13-alpine
    # Reinicia o container automaticamente a menos que ele seja parado explicitamente
    restart: unless-stopped
    environment: # Variáveis de ambiente para o banco de dados
      POSTGRES_DB: guessgame
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app_network

  # Serviço do Backend Python (Flask)
  backend:
    build: ./backend
    # Reinicia o container automaticamente a menos que ele seja parado explicitamente
    restart: unless-stopped
    environment:
      #DATABASE_URL: postgresql://user:password@db:5432/guessgame
      DB_TYPE: postgres # <--- AGORA ESTÁ USANDO A VARIAVEL CORRETA
      DB_NAME: guessgame # Nome do banco de dados (igual ao definido no serviço 'db')
      DB_USER: user # Usuário do banco de dados (igual ao definido no serviço 'db')
      DB_PASSWORD: password # Senha do banco de dados (igual ao definido no serviço 'db')
      DB_HOST: db # Host do banco de dados (nome do serviço 'db' no docker-compose)

      FLASK_APP: run.py
      FLASK_ENV: production


    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - app_network

  # Serviço do Frontend React (servido via NGINX como proxy reverso)
  frontend:
    build:
      context: ./frontend # Onde o Dockerfile e o código do frontend estão
      args:
        REACT_APP_BACKEND_URL: http://localhost:5000
    # Reinicia o container automaticamente a menos que ele seja parado explicitamente
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend #para garantir que o backend esteja up antes do frontend.
    networks:
      - app_network

# Define os volumes para persistência de dados
volumes:
  db_data:

# Define as redes personalizadas para a comunicação entre os serviços
networks:
  app_network:
    driver: bridge